version: '3.8'
services:
  dev-db:
    image: postgres:13.11-bullseye
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: job
    networks:
      - nestss
networks:
  nestss:
